name: CI

on:
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          wget https://github.com/archiecobbs/logwarn/archive/refs/tags/1.0.16.tar.gz
          tar xf 1.0.16.tar.gz
          cd logwarn-1.0.16
          ./autogen.sh && ./configure --prefix=/tmp/logwarn && make && make install

      - run: |
          PATH=/tmp/logwarn/bin:$PATH prove -v ./test_logwarn
